regen

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19715,6 +19715,12 @@ _ACEOF
 fi
 
 fi
+if test "x$LEX" = "x:"
+then
+	{ { echo "$as_me:$LINENO: error: No flex nor lex found, please install flex first." >&5
+echo "$as_me: error: No flex nor lex found, please install flex first." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -19755,6 +19761,55 @@ fi
   test -n "$YACC" && break
 done
 test -n "$YACC" || YACC="yacc"
+
+if test "$YACC" = "yacc"
+then
+	# Extract the first word of "$YACC", so it can be a program name with args.
+set dummy $YACC; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_YACC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $YACC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_YACC="$YACC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_YACC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+YACC=$ac_cv_path_YACC
+
+if test -n "$YACC"; then
+  echo "$as_me:$LINENO: result: $YACC" >&5
+echo "${ECHO_T}$YACC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+	if test "x$YACC" = "x"
+	then
+		{ { echo "$as_me:$LINENO: error: No bison nor yacc found, please install bison first." >&5
+echo "$as_me: error: No bison nor yacc found, please install bison first." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+fi
 
 # Find a good install program.  We prefer a C program (faster),
 # so one script is as good as another.  But avoid the broken or
